INSERT INTO BOOKS ( ID , AUTHOR , ISBN , PUBLISH_DATE , TITLE ) VALUES (1,'TEST AUTHOR1','TESTISBN1','2001-01-01','TEST KITAP 1');
INSERT INTO BOOKS ( ID , AUTHOR , ISBN , PUBLISH_DATE , TITLE ) VALUES (2,'TEST AUTHOR2','TESTISBN2','2002-01-01','TEST KITAP 2');
INSERT INTO BOOKS ( ID , AUTHOR , ISBN , PUBLISH_DATE , TITLE ) VALUES (3,'TEST AUTHOR3','TESTISBN3','2003-01-01','TEST KITAP 3');